### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by directx5** [FerrisComplex/ferriscomplex.github.io#2]
# Champions

- ## Zed
    - Holding combo key when W shadow is valid (W2 is ready) causes fps drops (this doesn't happens with R shadow).
    - Sometimes casts Q to last seen position of enemy, even while I can see there is no enemy at that position.
    - Even if R is casted, does not continue the combo without casting W, waits for W to be casted for Q.
    - There is no option to close killsteal.

---
	
# General

- Takes so long to load (15-20 seconds).
- Average fps is 45.

**Comment by gogoing1024** [comment]
Urgot
R simit key is error

**Comment by FerrisComplex** [comment]
>   * Holding combo key when W shadow is valid (W2 is ready) causes fps drops (this doesn't happens with R shadow).

This should mostly be fixed in 1.0.0.30
>   * Sometimes casts Q to last seen position of enemy, even while I can see there is no enemy at that position.

This has been fixed, killsteal has no range checks
>   * Even if R is casted, does not continue the combo without casting W, waits for W to be casted for Q.

Am aware of this and will fix in 1.0.0.31
>   * There is no option to close killsteal.

Killsteal options have been added

> * Takes so long to load (15-20 seconds).

This has been resolved in the latest builds of ensoul and should no longer be an ssue
> * Average fps is 45.

Average FPS has more than trippled for most testers in 1.0.0.30 should fully resolve most of the poor FPS issues throught

Sorry for the late response but thanks for the feedback <3

**Comment by gogoing1024** [comment]
============================================================================
Cause: firstchance
Character: Irelia
Map: SummonersRift(SummonersRift)
Script Loaded: Yes
Prediction Type: Ferris
OrbwalkerV1 Active: Yes
OrbwalkerV2 Active: No
Timestamp: 2021-08-21 12:07:02 PM
Version: 1.0.0.29
----------------------------------------------------------------------------
Collection was modified; enumeration operation may not execute.
----------------------------------------------------------------------------
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at EnsoulSharp.SDK.MenuUI.Menu.OnWndProc(WindowsKeys args)
============================================================================

============================================================================
Cause: firstchance
Character: Irelia
Map: SummonersRift(SummonersRift)
Script Loaded: Yes
Prediction Type: Ferris
OrbwalkerV1 Active: Yes
OrbwalkerV2 Active: No
Timestamp: 2021-08-21 12:10:58 PM
Version: 1.0.0.29
----------------------------------------------------------------------------
Exception of type 'EnsoulSharp.GameObjectNotFoundException' was thrown.
----------------------------------------------------------------------------
   at EnsoulSharp.GameObject.GetPtr()
   at EnsoulSharp.GameObject.get_IsValid()
============================================================================
