### ISSUE TITLE
orb make kaisa to drop anmation while use E

### ISSUE THREAD

**Issue by yanghoxom** [FerrisComplex/ferriscomplex.github.io#8]
When use FE orbwalker,
hold combo / farm
use E of kaisa
it seems orbwalker trying to hit and run, cancel animation,.. while kaisa charging E, it make kaisa stop constantly

**Comment by ChrisVineyard-abc** [comment]
> When use FE orbwalker, hold combo / farm use E of kaisa it seems orbwalker trying to hit and run, cancel animation,.. while kaisa charging E, it make kaisa stop constantly

I think FE Orb is not the problem, bcs I just use SDK orb and still has this issue

**Comment by yanghoxom** [comment]
@ChrisVineyard-abc  I do not face this problem while use default orb

**Comment by ChrisVineyard-abc** [comment]
> @ChrisVineyard-abc I do not face this problem while use default orb

Which author do you use?

**Comment by yanghoxom** [comment]
@ChrisVineyard-abc 
default orb + zaio : ok
zaio + ferris orb => bug when charging E
