### ISSUE TITLE
VEX

### ISSUE THREAD

**Issue by deniz3131** [FerrisComplex/ferriscomplex.github.io#9]
vex combo so bad and so slow q,e,r :/

**Comment by FerrisComplex** [comment]
Am aware this will be updated in the next few days

**Comment by SpaceLeft** [comment]
vayne support?

**Comment by FerrisComplex** [comment]
> vayne support?

vayne is supported but is pending a rewrite to improve it a fair bit

**Comment by SpaceLeft** [comment]
@FerrisComplex, i get 
in `folder, game name ferrisAIO_errorlog2`
============================================================================
Cause: firstchance
Game Version: 11.24.413.2485
Character: Caitlyn
Acitve Mode: Flee
Map: SummonersRift(11)
Script Loaded: Yes
Prediction Type: Ferris
OrbwalkerV1 Active: Yes
OrbwalkerV2 Active: No
Timestamp: 2021-12-14 10:08:48 PM
Version: 1.0.0.38
----------------------------------------------------------------------------
Collection was modified; enumeration operation may not execute.
----------------------------------------------------------------------------
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at EnsoulSharp.SDK.MenuUI.Menu.OnWndProc(WindowsKeys args)
============================================================================

============================================================================
Cause: firstchance
Game Version: 11.24.413.2485
Character: Caitlyn
Acitve Mode: Flee
Map: SummonersRift(11)
Script Loaded: Yes
Prediction Type: Ferris
OrbwalkerV1 Active: Yes
OrbwalkerV2 Active: No
Timestamp: 2021-12-14 10:08:52 PM
Version: 1.0.0.38
----------------------------------------------------------------------------
Method not found: 'Double EnsoulSharp.SDK.Damage.GetAutoAttackDamage(EnsoulSharp.AIBaseClient, EnsoulSharp.AIBaseClient, Boolean)'.
----------------------------------------------------------------------------
   at ᅠ40DEBC68F49E555D6AB83391C70E2E6B.ᅠ93B81C15A65EEAC48696A9A535C0CBFE(AIBaseClient , AIBaseClient , Boolean )
   at ᅠ40DEBC68F49E555D6AB83391C70E2E6B.ᅠ165CEB0CC10B4DB16B38C359068606B9(AIBaseClient , AIBaseClient , Boolean )
============================================================================
